#!/usr/bin/env python3
import os

from src.ConfigSettings import parse_config
from src.DatabaseMethods import set_up_db
from src.MoodliArgumentParser import get_parser


def main():
    try:
        parse_config()
        set_up_db()
        parser = get_parser()
        args = parser.parse_args()
        args.func(args)
    except Exception as exception:
        raise exception
    finally:
        if os.path.exists(os.path.join('/', 'tmp', 'moodli.db')):
            os.remove(os.path.join('/', 'tmp', 'moodli.db'))


if __name__ == '__main__':
    main()
